feat: remote instances require all requests to be signed (closes #16)
hyphacoop/social.distributed.press pull request #20
Opened 2023-11-08 19:22 UTC by akhileshthite

2023-11-08 19:38 UTC, fauno commented
Please let me know when this is deployed so we can run tests

2023-11-09 16:47 UTC, RangerMauve requested changes

2023-11-09 16:47 UTC, RangerMauve commented on src/server/apsystem.ts
> +    const response = await this.signedFetch(this.publicURL, {
We cannot use the publicURL as an actor, we need to modify the method to pass in a `fromActor` parameter which represents the actor we're fetching this data on behalf of.

2023-11-13 17:18 UTC, RangerMauve requested changes

2023-11-14 17:23 UTC, RangerMauve approved these changes
Excellent, thank you!

2023-11-14 17:23 UTC, merged