paginated inbox
hyphacoop/social.distributed.press pull request #63
Opened 2024-05-16 19:40 UTC by catdevnull

fixes #163

- [ ] add some way to automatically add indexes to existing inboxes

2024-05-28 21:00 UTC, catdevnull commented on src/server/store/ActivityStore.ts
> +    await this.publishedIndex.put(`${publishedAt.toISOString()}-${id}`, id)
I'm believe toISOString produces sortable strings:

>The toISOString() method of Date instances returns a string representing this date in the date time string format, a simplified format based on ISO 8601

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString

>Date and time values are ordered from the largest to smallest unit of time: year, month (or week), day, hour, minute, second, and fraction of second. The lexicographical order of the representation thus corresponds to chronological order

https://en.wikipedia.org/wiki/ISO_8601

2024-05-28 21:08 UTC, catdevnull commented on src/server/store/ActivityStore.ts
> +    for await (const _ of this.db.keys()) { // eslint-disable-line @typescript-eslint/no-unused-vars
I'm not sure how the test would be implemented. As I understand it, this wouldn't be possible, as sublevels are entirely different databases, right?

2024-05-29 17:38 UTC, RangerMauve commented on src/server/store/ActivityStore.ts
> +    for await (const _ of this.db.keys()) { // eslint-disable-line @typescript-eslint/no-unused-vars
Just test that after inserting three documents the count is three.

2024-05-29 17:39 UTC, RangerMauve commented on src/server/store/ActivityStore.ts
> +    for await (const _ of this.db.keys()) { // eslint-disable-line @typescript-eslint/no-unused-vars
Sublevels are key prexfixes over the parent database.

e.g. `sub(db, "example")` would prefix all keys with `example`. that way you can more easily partition the key space.

2024-05-29 17:44 UTC, RangerMauve requested changes
Great! Lets just get some small tests in to make sure it's working and then it looks good to me. :)

2024-05-29 17:44 UTC, RangerMauve commented on src/server/store/ActivityStore.ts
> +    await this.removeFromIndex(url)
We should remove from the index before the del, else it won't be able to fetch the doc.

Mind adding a test for this? With a fresh store: Add a doc, remove the doc by url, test that there are no index keys and no docs.

2024-06-04 20:57 UTC, RangerMauve commented on src/server/store/ActivityStore.ts
> +    for await (const _ of this.db.keys()) { // eslint-disable-line @typescript-eslint/no-unused-vars
This was the case, only affected the migration script. Fixed.

2024-06-04 20:57 UTC, RangerMauve commented on src/server/store/ActivityStore.ts
> +    await this.removeFromIndex(url)
Fixed tests, modified list test to check ordering.

2024-06-04 21:15 UTC, merged