Process announcements inbox on boot.
hyphacoop/social.distributed.press pull request #69
Opened 2024-06-24 21:03 UTC by RangerMauve

This should fix some of the issues we've had with folks not being able to subscribe effectively.

2024-06-24 21:11 UTC, fauno requested changes

2024-06-24 21:11 UTC, fauno commented on src/server/announcements.ts
> +      summary: `Subscribe to get notifid about new accounts hosted at ${url}`,
small typo :B

2024-06-24 21:20 UTC, akhileshthite approved these changes
looks good!

2024-07-08 17:33 UTC, RangerMauve commented
Gonna try to handle this again.

2024-07-08 21:09 UTC, merged